name: Module CI

on:
  push:
  pull_request:

jobs:
  ci:
    name: CI
    uses: silverstripe/gha-ci/.github/workflows/ci.yml@v1
    with:
      endtoend: false
      composer_require_extra: silverstripe/installer:4.13.x-dev
      simple_matrix: true
